/*
connectors-api

HTTP server that handle connectors.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gosdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectorPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorPutRequest{}

// ConnectorPutRequest struct for ConnectorPutRequest
type ConnectorPutRequest struct {
	Name string `json:"name"`
	Displayname string `json:"displayname"`
	Url string `json:"url"`
}

type _ConnectorPutRequest ConnectorPutRequest

// NewConnectorPutRequest instantiates a new ConnectorPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorPutRequest(name string, displayname string, url string) *ConnectorPutRequest {
	this := ConnectorPutRequest{}
	this.Name = name
	this.Displayname = displayname
	this.Url = url
	return &this
}

// NewConnectorPutRequestWithDefaults instantiates a new ConnectorPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorPutRequestWithDefaults() *ConnectorPutRequest {
	this := ConnectorPutRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ConnectorPutRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectorPutRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectorPutRequest) SetName(v string) {
	o.Name = v
}

// GetDisplayname returns the Displayname field value
func (o *ConnectorPutRequest) GetDisplayname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Displayname
}

// GetDisplaynameOk returns a tuple with the Displayname field value
// and a boolean to check if the value has been set.
func (o *ConnectorPutRequest) GetDisplaynameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Displayname, true
}

// SetDisplayname sets field value
func (o *ConnectorPutRequest) SetDisplayname(v string) {
	o.Displayname = v
}

// GetUrl returns the Url field value
func (o *ConnectorPutRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ConnectorPutRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ConnectorPutRequest) SetUrl(v string) {
	o.Url = v
}

func (o ConnectorPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayname"] = o.Displayname
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ConnectorPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"displayname",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorPutRequest := _ConnectorPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorPutRequest)

	if err != nil {
		return err
	}

	*o = ConnectorPutRequest(varConnectorPutRequest)

	return err
}

type NullableConnectorPutRequest struct {
	value *ConnectorPutRequest
	isSet bool
}

func (v NullableConnectorPutRequest) Get() *ConnectorPutRequest {
	return v.value
}

func (v *NullableConnectorPutRequest) Set(val *ConnectorPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorPutRequest(val *ConnectorPutRequest) *NullableConnectorPutRequest {
	return &NullableConnectorPutRequest{value: val, isSet: true}
}

func (v NullableConnectorPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


